version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: ACCESS_KEY_ID
          aws-secret-access-key: SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          region: AWS_REGION
          repo: ${ECRRepository}
          skip-when-tags-exist: false
          tag: 'latest'
          filters:
            branches:
              only: master
